### ISSUE TITLE
Single fire missile only works once

### ISSUE THREAD

**Issue by alexeijd** [l0k1/MiG-21bis#10]
ripple fire works ok

single fire works on the 1st instance (doesn't matter which pylon is selected) but throws up this error after launching the 1st/hitting the target:

Nasal runtime error: non-objects have no members
at MiG-21bis/Nasal/payloads.nas, line 371

no more errors show in the logs, selecting ripple fire doesn't work either

**Comment by l0k1** [comment]
Ahh shoot. This was borked by the impact_report() function that was re-enabled in #8 - we'll need to pass the missile name as well (or check if typeOrd is nil in payloads, but that's a little more hacky).

**Comment by alexeijd** [comment]
OK - I think the F-14 passes missile name in it's impact_report() function
- I'll have a look at that

**Comment by alexeijd** [comment]
Well it worked fine before I pulled everything up to the latest tree - the only thing I hadn't tested was ripple fire (and of course no bombs)

The following small patch doesn't fix the problem:


--- a/Nasal/guided-missiles.nas
+++ b/Nasal/guided-missiles.nas
@@ -1357,7 +1357,7 @@ var AIM = {
                #me.t_coord.set_alt(new_t_alt_m);               
                var wh_mass = me.weight_whead_lbs / slugs_to_lbs;
                #print("FOX2: me.direct_dist_m = ",  me.direct_dist_m, " time ",getprop("sim/time/elapsed-sec"));
-               impact_report(me.coord, wh_mass, "missile"); # pos, alt, mass_slug,(speed_mps)
+               impact_report(me.coord, wh_mass, "missile", me.type); # pos, alt, mass_slug,(speed_mps)
 
                var phrase = sprintf( me.type~" exploded: %01.1f", min_distance) ~ " meters from: " ~ me.callsign;
                print(phrase~"  Reason: "~reason~sprintf(" time %.1f", me.life_time));
@@ -1674,7 +1674,7 @@ var AIM = {
 #valid "true" BOOL
 
 
-var impact_report = func(pos, mass_slug, string) {
+var impact_report = func(pos, mass_slug, string, name) {
 
        # Find the next index for "ai/models/model-impact" and create property node.
        var n = props.globals.getNode("ai/models", 1);
@@ -1690,6 +1690,7 @@ var impact_report = func(pos, mass_slug, string) {
        #impact.getNode("speed-mps", 1).setValue(speed_mps);
        impact.getNode("valid", 1).setBoolValue(1);
        impact.getNode("impact/type", 1).setValue("terrain");
+        impact.getNode("name", 1).setValue(name);
 
        var impact_str = "/ai/models/" ~ string ~ "[" ~ i ~ "]";
        setprop("ai/models/model-impact", impact_str);


so passing the missile name isn't it and also disabling the impact_report doesn't fix it either

**Comment by l0k1** [comment]
Alright it should be fixed. I haven't tested it (I'm at work), but I'll test it as soon as I get a chance. Closing was accidental.

**Comment by l0k1** [comment]
Still broken. I've narrowed down the commit to ebfa2f47d5215816ff374dd4afcbfcd09be63f75 for sure. I'll keep working on this before the event.

**Comment by l0k1** [comment]
Found the error, should be fixed.
