### ISSUE TITLE
Smoke and explosions are duplicated

### ISSUE THREAD

**Issue by l0k1** [l0k1/MiG-21bis#3]
The missile smoke and missile explosions appear both at the pylon position and the missile position.

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/1434407/21083566/e9673002-bfa7-11e6-846d-b471f3a19a12.png)

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/1434407/21083567/ee1d1422-bfa7-11e6-8ffd-dd7f0e3b6fcf.png)

**Comment by l0k1** [comment]
Thanks to S for reporting, and @NikolaiVChr for finding the cause of the issue.

**Comment by NikolaiVChr** [comment]
No problem :)
