### ISSUE TITLE
Add radar view

### ISSUE THREAD

**Issue by l0k1** [l0k1/MiG-21bis#5]
Add a seperate view that focuses in on the radar screen.

Suggestion from discord chat by Sierra.

**Comment by NikolaiVChr** [comment]
Or, a floating dialog, with the radar canvas attached maybe? Then can look out the window and see radar at same time.

**Comment by l0k1** [comment]
@NikolaiVChr I'm hesitant to do that... I'm shooting for realism and I'm not in love with the idea. There will also be lights and other things going on immediately around the radar screen that aren't included in the canvas, that'll be missed if it's a separate window.
