### ISSUE TITLE
Incorrect path case for `tacview.nas`

### ISSUE THREAD

**Issue by colingeniet** [l0k1/MiG-21bis#53]
In `MiG-21-set-common.xml`, line 1739
```
<file>Aircraft/MIG-21bis/Nasal/tacview.nas</file>
```
should be
```
<file>Aircraft/MiG-21bis/Nasal/tacview.nas</file>
```
(incorrect case for the `i` in MiG).
Causes the file to fail to load, and a bunch of nasal errors in console, on case-sensitive file systems.

**Comment by l0k1** [comment]
Fixed, thanks!
