### ISSUE TITLE
Typo in gunsight algorithm

### ISSUE THREAD

**Issue by colingeniet** [l0k1/MiG-21bis#56]
In the AFALCOS implementation, there is a typo in the definition of W2: line 152 in
```
        me.W2 = me.W2 + (-me.SL1 * me.SL3 + me.C7 * me.SL3) * me._getP() + 
```
`-me.SL1 * me.SL3` should be `-me.SL1 * me.SL2` instead.

Corresponding code from the original paper, just in case:
`W2=W2+(-SL1*SL2+C7*SL3)*P+(1.-SL2**2)*Q-(SL2*SL3.C7*SL1 )*R`

**Comment by l0k1** [comment]
Thank you for this!
