### ISSUE TITLE
Missing model file 'tgtsphere.xml'

### ISSUE THREAD

**Issue by colingeniet** [l0k1/MiG-21bis#57]
In `Nasal/armament-locking.nas`, line 200 loads a model which doesn't exist:
```
objModel.getNode("path",1).setValue("Aircraft/MiG-21bis/Models/tgtsphere.xml"); # this is the model to be loaded.
```

This generates a constant flow of `Error in reading file  : file not handled` messages in the console.

**Comment by l0k1** [comment]
I wasn't seeing these errors on my end, but I've commented it out nonetheless. Thanks!
