### ISSUE TITLE
Kh-66 nasal error

### ISSUE THREAD

**Issue by colingeniet** [l0k1/MiG-21bis#59]
I have the following error when firing a Kh-66:
```
  269.56 [INFO]:nasal      multi-threading error:
  269.56 [INFO]:nasal      No such member: get_uBody
  269.56 [INFO]:nasal      /home/colin/flightgear/Aircraft/MiG-21bis/Nasal/guided-missiles.nas
  269.56 [INFO]:nasal      3515
  269.56 [INFO]:nasal      /home/colin/flightgear/Aircraft/MiG-21bis/Nasal/guided-missiles.nas
  269.56 [INFO]:nasal      2873
  269.56 [INFO]:nasal      /home/colin/flightgear/Aircraft/MiG-21bis/Nasal/guided-missiles.nas
  269.56 [INFO]:nasal      2106
```
If I did not mess up, my radar was in beam mode (on radar panel: left switch up, middle switch down, right switch up).
When firing with radar turned off, the error doesn't occur and the missile works correctly, but is of course unguided.

**Comment by l0k1** [comment]
Alright, the nasal error was fixed with 04a18c6, and they track with the gunsight, but they are tracking lower than they should be. I'll need to look into this a little more, but for now, just aim higher than what you want to hit.
